### ISSUE TITLE
Display own PeerId in Web

### ISSUE THREAD

**Issue by elenaf9** [elenaf9/internet-communication-swp#11]
The web should be able to query the management component for its own PeerId, so that the user can share it with other peers for whitelisting.

**Comment by elenaf9** [comment]
Implemented in 36b09ad.

**Comment by lowski** [comment]
that commit is not on any branch - can you merge this onto main please?

**Comment by elenaf9** [comment]
I did push it to main yesterday. I guess somebody accidentally force-pushed to main and overwrote my commit. Pushed it again.
