### ISSUE TITLE
Add nice table to web component

### ISSUE THREAD

**Issue by lowski** [elenaf9/internet-communication-swp#9]
The web component should make sending a table to a node simple. So a nice (bootstrap?) table where you can add and remove rows and columns should be added. Additionally there needs to be a way to enter the peer id to send the table to.

The JS should create the correctly formatted string (`send <node> <table>`) and send it to the management component.

**Comment by elenaf9** [comment]
Implemented with 63130e9c99237d20a3a321aff4ca9aa016888aa4 and 36b09ad.
